/**
 * Unified component type definitions combining display names, layer metadata, and entity query information.
 * Single source of truth for all 132+ Dataverse component types.
 */

import { ComponentType } from "../types/componentType";

export type { ComponentType };

export const COMPONENT_TYPES: ComponentType[] = [
  {
    solutioncomponenttype: 1,
    name: "Entity",
    layerName: "Entity",
    entityLogicalName: "entity",
    tableName: "entities",
    idField: "entityid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 2,
    name: "Attribute",
    layerName: "Attribute",
    entityLogicalName: "attribute",
    tableName: "attributes",
    idField: "attributeid",
    displayField: "logicalname",
  },
  {
    solutioncomponenttype: 3,
    name: "Relationship",
    layerName: "Relationship",
    entityLogicalName: "relationship",
    tableName: "relationships",
    idField: "relationshipid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 4,
    name: "AttributePicklistValue",
    layerName: "AttributePicklistValue",
    entityLogicalName: "attributepicklistvalue",
    tableName: "optionsets",
    idField: "optionsetid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 5,
    name: "AttributeLookupValue",
    layerName: "AttributeLookupValue",
    entityLogicalName: "attributelookupvalue",
    tableName: "workflows",
    idField: "workflowid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 6,
    name: "ViewAttribute",
    layerName: "ViewAttribute",
    entityLogicalName: "viewattribute",
    tableName: "reports",
    idField: "reportid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 7,
    name: "LocalizedLabel",
    layerName: "LocalizedLabel",
    entityLogicalName: "localizedlabel",
    tableName: "reportcategories",
    idField: "reportcategoryid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 8,
    name: "RelationshipExtraCondition",
    layerName: "RelationshipExtraCondition",
    entityLogicalName: "relationshipextracondition",
    tableName: "systemusers",
    idField: "systemuserid",
    displayField: "fullname",
  },
  {
    solutioncomponenttype: 9,
    name: "OptionSet",
    layerName: "OptionSet",
    entityLogicalName: "optionset",
    tableName: "roles",
    idField: "roleid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 10,
    name: "EntityRelationship",
    layerName: "EntityRelationship",
    entityLogicalName: "entityrelationship",
    tableName: "roleprivileges",
    idField: "roleprivilegeid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 11,
    name: "EntityRelationshipRole",
    layerName: "EntityRelationshipRole",
    entityLogicalName: "entityrelationshiprole",
  },
  {
    solutioncomponenttype: 12,
    name: "EntityRelationshipRelationships",
    layerName: "EntityRelationshipRelationships",
    entityLogicalName: "entityrelationshiprelationships",
    tableName: "systemforms",
    idField: "formid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 13,
    name: "ManagedProperty",
    layerName: "ManagedProperty",
    entityLogicalName: "managedproperty",
    tableName: "visualizations",
    idField: "visualizationid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 14,
    name: "EntityKey",
    layerName: "EntityKey",
    entityLogicalName: "entitykey",
    tableName: "dashboards",
    idField: "dashboardid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 16,
    name: "Privilege",
    layerName: "Privilege",
    entityLogicalName: "privilege",
    tableName: "subscriptions",
    idField: "subscriptionid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 17,
    name: "PrivilegeObjectTypeCode",
    layerName: "PrivilegeObjectTypeCode",
    entityLogicalName: "privilegeobjecttypecode",
  },
  {
    solutioncomponenttype: 18,
    name: "Index",
    layerName: "Index",
    entityLogicalName: "index",
    tableName: "fieldpermissions",
    idField: "fieldpermissionid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 19,
    name: "Reserved",
    layerName: "Reserved",
    entityLogicalName: "reserved",
    tableName: "sharepointdocumentlocations",
    idField: "sharepointdocumentlocationid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 20,
    name: "Role",
    layerName: "Role",
    entityLogicalName: "role",
    tableName: "sharepointsites",
    idField: "sharepointsiteid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 21,
    name: "RolePrivilege",
    layerName: "RolePrivilege",
    entityLogicalName: "roleprivilege",
    tableName: "webresources",
    idField: "webresourceid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 22,
    name: "DisplayString",
    layerName: "DisplayString",
    entityLogicalName: "displaystring",
    tableName: "customcontrols",
    idField: "customcontrolid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 23,
    name: "DisplayStringMap",
    layerName: "DisplayStringMap",
    entityLogicalName: "displaystringmap",
  },
  {
    solutioncomponenttype: 24,
    name: "Form",
    layerName: "Form",
    entityLogicalName: "systemform",
  },
  {
    solutioncomponenttype: 25,
    name: "Organization",
    layerName: "Organization",
    entityLogicalName: "organization",
    tableName: "connectionroles",
    idField: "connectionroleid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 26,
    name: "SavedQuery",
    layerName: "SavedQuery",
    entityLogicalName: "savedquery",
  },
  {
    solutioncomponenttype: 29,
    name: "Workflow",
    layerName: "Workflow",
    entityLogicalName: "workflow",
  },
  {
    solutioncomponenttype: 31,
    name: "Report",
    layerName: "Report",
    entityLogicalName: "report",
    tableName: "notifications",
    idField: "notificationid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 32,
    name: "ReportEntity",
    layerName: "ReportEntity",
    entityLogicalName: "reportentity",
  },
  {
    solutioncomponenttype: 33,
    name: "ReportCategory",
    layerName: "ReportCategory",
    entityLogicalName: "reportcategory",
  },
  {
    solutioncomponenttype: 34,
    name: "ReportVisibility",
    layerName: "ReportVisibility",
    entityLogicalName: "reportvisibility",
  },
  {
    solutioncomponenttype: 35,
    name: "Attachment",
    layerName: "Attachment",
    entityLogicalName: "attachment",
  },
  {
    solutioncomponenttype: 36,
    name: "EmailTemplate",
    layerName: "EmailTemplate",
    entityLogicalName: "emailtemplate",
  },
  {
    solutioncomponenttype: 37,
    name: "ContractTemplate",
    layerName: "ContractTemplate",
    entityLogicalName: "contracttemplate",
  },
  {
    solutioncomponenttype: 38,
    name: "KBArticleTemplate",
    layerName: "KBArticleTemplate",
    entityLogicalName: "kbarticletemplate",
  },
  {
    solutioncomponenttype: 39,
    name: "MailMergeTemplate",
    layerName: "MailMergeTemplate",
    entityLogicalName: "mailmergetemplate",
  },
  {
    solutioncomponenttype: 44,
    name: "DuplicateRule",
    layerName: "DuplicateRule",
    entityLogicalName: "duplicaterule",
  },
  {
    solutioncomponenttype: 45,
    name: "DuplicateRuleCondition",
    layerName: "DuplicateRuleCondition",
    entityLogicalName: "duplicaterulecondition",
  },
  {
    solutioncomponenttype: 46,
    name: "EntityMap",
    layerName: "EntityMap",
    entityLogicalName: "entitymap",
  },
  {
    solutioncomponenttype: 47,
    name: "AttributeMap",
    layerName: "AttributeMap",
    entityLogicalName: "attributemap",
  },
  {
    solutioncomponenttype: 48,
    name: "RibbonCommand",
    layerName: "RibbonCommand",
    entityLogicalName: "ribboncommand",
  },
  {
    solutioncomponenttype: 49,
    name: "RibbonContextGroup",
    layerName: "RibbonContextGroup",
    entityLogicalName: "ribboncontextgroup",
  },
  {
    solutioncomponenttype: 50,
    name: "RibbonCustomization",
    layerName: "RibbonCustomization",
    entityLogicalName: "ribboncustomization",
  },
  {
    solutioncomponenttype: 52,
    name: "RibbonRule",
    layerName: "RibbonRule",
    entityLogicalName: "ribbonrule",
  },
  {
    solutioncomponenttype: 53,
    name: "RibbonTabToCommandMap",
    layerName: "RibbonTabToCommandMap",
    entityLogicalName: "ribbontabtocommandmap",
  },
  {
    solutioncomponenttype: 55,
    name: "RibbonDiff",
    layerName: "RibbonDiff",
    entityLogicalName: "ribbondiff",
  },
  {
    solutioncomponenttype: 59,
    name: "SavedQueryVisualization",
    layerName: "SavedQueryVisualization",
    entityLogicalName: "savedqueryvisualization",
  },
  {
    solutioncomponenttype: 60,
    name: "SystemForm",
    layerName: "SystemForm",
    entityLogicalName: "systemform",
    tableName: "systemforms",
    idField: "formid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 61,
    name: "WebResource",
    layerName: "WebResource",
    entityLogicalName: "webresource",
    tableName: "canvasapps",
    idField: "canvasappid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 62,
    name: "SiteMap",
    layerName: "SiteMap",
    entityLogicalName: "sitemap",
  },
  {
    solutioncomponenttype: 63,
    name: "ConnectionRole",
    layerName: "ConnectionRole",
    entityLogicalName: "connectionrole",
  },
  {
    solutioncomponenttype: 64,
    name: "ComplexControl",
    layerName: "ComplexControl",
    entityLogicalName: "complexcontrol",
  },
  {
    solutioncomponenttype: 65,
    name: "HierarchyRule",
    layerName: "HierarchyRule",
    entityLogicalName: "hierarchyrule",
  },
  {
    solutioncomponenttype: 66,
    name: "CustomControl",
    layerName: "CustomControl",
    entityLogicalName: "customcontrol",
  },
  {
    solutioncomponenttype: 68,
    name: "CustomControlDefaultConfig",
    layerName: "CustomControlDefaultConfig",
    entityLogicalName: "customcontroldefaultconfig",
  },
  {
    solutioncomponenttype: 70,
    name: "FieldSecurityProfile",
    layerName: "FieldSecurityProfile",
    entityLogicalName: "fieldsecurityprofile",
  },
  {
    solutioncomponenttype: 71,
    name: "FieldPermission",
    layerName: "FieldPermission",
    entityLogicalName: "fieldpermission",
  },
  {
    solutioncomponenttype: 80,
    name: "AppModule",
    layerName: "AppModule",
    entityLogicalName: "appmodule",
    tableName: "sdkmessages",
    idField: "sdkmessageid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 90,
    name: "PluginType",
    layerName: "PluginType",
    entityLogicalName: "plugintype",
    tableName: "sdkmessagefilters",
    idField: "sdkmessagefilterid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 91,
    name: "PluginAssembly",
    layerName: "PluginAssembly",
    entityLogicalName: "pluginassembly",
    tableName: "sdkmessageprocessingsteps",
    idField: "sdkmessageprocessingstepid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 92,
    name: "SdkMessageProcessingStep",
    layerName: "SdkMessageProcessingStep",
    entityLogicalName: "sdkmessageprocessingstep",
    tableName: "sdkmessageprocessingstepimages",
    idField: "sdkmessageprocessingstepimageid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 93,
    name: "SdkMessageProcessingStepImage",
    layerName: "SdkMessageProcessingStepImage",
    entityLogicalName: "sdkmessageprocessingstepimage",
    tableName: "serviceendpoints",
    idField: "serviceendpointid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 95,
    name: "ServiceEndpoint",
    layerName: "ServiceEndpoint",
    entityLogicalName: "serviceendpoint",
  },
  {
    solutioncomponenttype: 150,
    name: "RoutingRule",
    layerName: "RoutingRule",
    entityLogicalName: "routingrule",
  },
  {
    solutioncomponenttype: 151,
    name: "RoutingRuleItem",
    layerName: "RoutingRuleItem",
    entityLogicalName: "routingruleitem",
  },
  {
    solutioncomponenttype: 152,
    name: "SLA",
    layerName: "SLA",
    entityLogicalName: "sla",
  },
  {
    solutioncomponenttype: 153,
    name: "SLAItem",
    layerName: "SLAItem",
    entityLogicalName: "slaitem",
  },
  {
    solutioncomponenttype: 154,
    name: "ConvertRule",
    layerName: "ConvertRule",
    entityLogicalName: "convertrule",
  },
  {
    solutioncomponenttype: 155,
    name: "ConvertRuleItem",
    layerName: "ConvertRuleItem",
    entityLogicalName: "convertruleitem",
  },
  {
    solutioncomponenttype: 161,
    name: "MobileOfflineProfile",
    layerName: "MobileOfflineProfile",
    entityLogicalName: "mobileofflineprofile",
  },
  {
    solutioncomponenttype: 162,
    name: "MobileOfflineProfileItem",
    layerName: "MobileOfflineProfileItem",
    entityLogicalName: "mobileofflineprofileitem",
    tableName: "connectionreferences",
    idField: "connectionreferenceid",
    displayField: "connectionreferenceid",
  },
  {
    solutioncomponenttype: 165,
    name: "SimilarityRule",
    layerName: "SimilarityRule",
    entityLogicalName: "similarityrule",
  },
  {
    solutioncomponenttype: 166,
    name: "DataSourceMapping",
    layerName: "DataSourceMapping",
    entityLogicalName: "datasourcemapping",
  },
  {
    solutioncomponenttype: 201,
    name: "SDKMessage",
    layerName: "SDKMessage",
    entityLogicalName: "sdkmessage",
  },
  {
    solutioncomponenttype: 202,
    name: "SDKMessageFilter",
    layerName: "SDKMessageFilter",
    entityLogicalName: "sdkmessagefilter",
  },
  {
    solutioncomponenttype: 203,
    name: "SdkMessagePair",
    layerName: "SdkMessagePair",
    entityLogicalName: "sdkmessagepair",
  },
  {
    solutioncomponenttype: 204,
    name: "SdkMessageRequest",
    layerName: "SdkMessageRequest",
    entityLogicalName: "sdkmessagerequest",
  },
  {
    solutioncomponenttype: 205,
    name: "SdkMessageRequestField",
    layerName: "SdkMessageRequestField",
    entityLogicalName: "sdkmessagerequestfield",
  },
  {
    solutioncomponenttype: 206,
    name: "SdkMessageResponse",
    layerName: "SdkMessageResponse",
    entityLogicalName: "sdkmessageresponse",
  },
  {
    solutioncomponenttype: 207,
    name: "SdkMessageResponseField",
    layerName: "SdkMessageResponseField",
    entityLogicalName: "sdkmessageresponsefield",
  },
  {
    solutioncomponenttype: 208,
    name: "ImportMap",
    layerName: "ImportMap",
    entityLogicalName: "importmap",
  },
  {
    solutioncomponenttype: 210,
    name: "WebWizard",
    layerName: "WebWizard",
    entityLogicalName: "webwizard",
  },
  {
    solutioncomponenttype: 236,
    name: "Team",
    layerName: "Team",
    entityLogicalName: "team",
    tableName: "teams",
    idField: "teamid",
    displayField: "name",
  },
  {
    solutioncomponenttype: 300,
    name: "CanvasApp",
    layerName: "CanvasApp",
    entityLogicalName: "canvasapp",
  },
  {
    solutioncomponenttype: 319,
    name: "AISkillConfiguration",
    layerName: "AISkillConfiguration",
    tableName: "msdyn_aiskillconfigs",
    idField: "msdyn_aiskillconfigid",
    displayField: "msdyn_skillname",
  },
  {
    solutioncomponenttype: 371,
    name: "Connector",
    layerName: "Connector",
    entityLogicalName: "connector",
  },
  {
    solutioncomponenttype: 372,
    name: "Connector",
    layerName: "Connector",
    entityLogicalName: "connector",
  },
  {
    solutioncomponenttype: 380,
    name: "EnvironmentVariableDefinition",
    layerName: "EnvironmentVariableDefinition",
    entityLogicalName: "environmentvariabledefinition",
  },
  {
    solutioncomponenttype: 381,
    name: "EnvironmentVariableValue",
    layerName: "EnvironmentVariableValue",
    entityLogicalName: "environmentvariablevalue",
  },
  {
    solutioncomponenttype: 400,
    name: "AIProjectType",
    layerName: "AIProjectType",
    entityLogicalName: "aiprojecttype",
  },
  {
    solutioncomponenttype: 401,
    name: "AIProject",
    layerName: "AIProject",
    entityLogicalName: "aiproject",
  },
  {
    solutioncomponenttype: 402,
    name: "AIConfiguration",
    layerName: "AIConfiguration",
    entityLogicalName: "aiconfiguration",
  },
  {
    solutioncomponenttype: 418,
    name: "Dataflow",
    layerName: "msdyn_dataflow",
    entityLogicalName: "msdyn_dataflow",
  },
  {
    solutioncomponenttype: 430,
    name: "EntityAnalyticsConfiguration",
    layerName: "EntityAnalyticsConfiguration",
    entityLogicalName: "entityanalyticsconfiguration",
  },
  {
    solutioncomponenttype: 431,
    name: "AttributeImageConfiguration",
    layerName: "AttributeImageConfiguration",
    entityLogicalName: "attributeimageconfiguration",
  },
  {
    solutioncomponenttype: 432,
    name: "EntityImageConfiguration",
    layerName: "EntityImageConfiguration",
    entityLogicalName: "entityimageconfiguration",
  },
];

/** Look up component type by numeric ID */
export const getComponentType = (typeNum: number): ComponentType | undefined =>
  COMPONENT_TYPES.find((c) => c.solutioncomponenttype === typeNum);

/** Get layer name for component type (for msdyn_componentlayers queries) */
export const getLayerName = (typeNum: number): string | undefined =>
  getComponentType(typeNum)?.layerName;

/** Get entity query metadata for component type */
export const getEntityInfo = (
  typeNum: number,
): { tableName: string; idField: string; displayField: string } | undefined => {
  const comp = getComponentType(typeNum);
  if (!comp?.tableName) return undefined;
  return {
    tableName: comp.tableName,
    idField: comp.idField!,
    displayField: comp.displayField!,
  };
};
